version: '3.8'

services:
  wnp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wnp
    ports:
      - "80:80"
    environment:
      - PORT=80
    volumes:
      - wnp-data:/var/lib/wiim-now-playing
    restart: unless-stopped

volumes:
  wnp-data:
